# Generated by Django 3.1.7 on 2021-03-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210326_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='products',
            new_name='category',
        ),
    ]
